apps/return_item/forms.py
from flask_wtf.form import FlaskForm
from wtforms.fields import DateField, SelectField, StringField, SubmitField

from apps.config import DOCUMENT, MINUTE, TIMES


# 遺失者連絡フォーム
class LostNote(FlaskForm):
    lost_date = DateField("遺失日")
    lost_hour = SelectField(
        label="遺失時間",
        choices=TIMES,
    )
    lost_minute = SelectField(
        label="受付時間(分)",
        choices=MINUTE,
    )
    lost_area = StringField("遺失場所")
    recep_item = DateField("受付日")
    recep_item_hour = SelectField(
        label="受付時間",
        choices=TIMES,
    )
    recep_item_minute = SelectField(
        label="受付時間(分)",
        choices=MINUTE,
    )
    recep_manager = SelectField("受付者", choices=[])
    lost_person = StringField("遺失者氏名")
    lost_class = StringField("遺失者属性")
    lost_affiliation = StringField("遺失者所属")
    lost_tel1 = StringField("連絡先1")
    lost_tel2 = StringField("連絡先2")
    lost_post = StringField("郵便番号")
    lost_address = StringField("住所")
    note_date = DateField("連絡日")
    note_hour = SelectField(
        label="連絡時間",
        choices=TIMES,
    )
    note_minute = SelectField(
        label="連絡時間",
        choices=MINUTE,
    )
    note_process = StringField("連絡手段/相手")
    note_manager = SelectField("連絡担当者", choices=[])
    response_date = DateField("返答日")
    response_hour = SelectField(
        label="返答時間",
        choices=TIMES,
    )
    response_minute = SelectField(
        label="返答時間",
        choices=MINUTE,
    )
    response_expect = DateField("返還予定日")
    response_content = StringField("返答内容")
    response_remarks = StringField("備考")
    submit = SubmitField("連絡完了")


# 返還フォーム
class ReturnItemForm(FlaskForm):
    return_date = DateField("返還日")
    return_check = SelectField(
        label="返答時間",
        choices=DOCUMENT,
    )
    return_person = StringField("返還者名")
    return_address = StringField("住所")
    return_tel = StringField("連絡先")
    return_manager = SelectField("返還担当者", choices=[])
    submit = SubmitField("返還")

apps/return_item/views.py
import os
from datetime import datetime
from pathlib import Path

from flask import Blueprint, redirect, render_template, url_for
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.pdfgen import canvas

from apps.app import db
from apps.crud.models import User
from apps.register.models import LostItem
from apps.return_item.forms import LostNote, ReturnItemForm

basedir = Path(__file__).parent.parent
UPLOAD_FOLDER = str(Path(basedir, "PDFfile"))

return_item = Blueprint(
    "return_item",
    __name__,
    template_folder="templates",
    static_folder="static",
)

basedir = Path(__file__).parent.parent
UPLOAD_FOLDER = str(Path(basedir, "PDFfile", "return_item_file"))

pdfmetrics.registerFont(UnicodeCIDFont('HeiseiMin-W3'))


# 受領書印刷
@return_item.route("/makepdf/<item_id>", methods=["POST", "GET"])
def make_pdf(item_id):
    lostitem = LostItem.query.filter_by(id=item_id).first()
    make_return_pdf(lostitem)
    return redirect(url_for("return_item.item", item_id=lostitem.id))


def make_return_pdf(item):
    current_time = datetime.now().strftime('%Y%m%d_%H%M%S')
    file_name = "return" + current_time + '.pdf'
    file_path = os.path.join(UPLOAD_FOLDER, file_name)
    p = canvas.Canvas(file_path, pagesize=A4)
    p.setFont('HeiseiMin-W3', 20)
    p.drawString(220, 800, "遺失物受領確認書")
    p.setFont('HeiseiMin-W3', 10)
    p.drawString(225, 790, "Confirmation receipt of Lost article")
    p.drawString(20, 770, "下記の遺失物確かに受領いたしました。")
    p.drawString(20, 758, "[I received the following lost article]")
    p.drawString(20, 730, "問い合わせ番号"), p.drawString(20, 718, "[Inquiry number]")
    p.drawString(30, 700, "受領日（返還日）"), p.drawString(30, 688,
                                                    "[Date recieved(Date of return)]")
    p.drawString(200, 695, "______年 ______月 ______日 ( ______ 曜日 )")
    p.drawString(30, 670, "受領時間"), p.drawString(30, 658, "[Time recieved]")
    p.drawString(200, 665, "______時 ______分")
    p.drawString(30, 640, "氏名"), p.drawString(30, 628, "[Name]")
    p.drawString(200, 635, "_______________________様       印")
    p.drawString(30, 610, "郵便番号"), p.drawString(30, 598, "[Post code]")
    p.drawString(200, 605, "〒_________ー_________")
    p.drawString(30, 580, "住所"), p.drawString(30, 568, "[Address]")
    p.drawString(200, 575, "__________________________________________________________")
    p.drawString(30, 550, "電話番号"), p.drawString(30, 538, "[Telephone number]")
    p.drawString(200, 545, "__________________________________")

    # 拾得物詳細
    p.drawString(20, 500, "拾得物詳細")
    p.drawString(30, 480, "管理No"), p.drawString(100, 480, str(item.main_id))
    p.drawString(30, 460, "拾得日")
    if item.get_item:
        p.drawString(100, 460, item.get_item.strftime('%Y/%m/%d'))
    p.drawString(30, 440, "拾得時間"), p.drawString(100, 440, item.get_item_hour)
    p.drawString(120, 440, item.get_item_minute)
    p.drawString(30, 420, "拾得場所"), p.drawString(100, 420, item.find_area)
    p.drawString(30, 400, "拾得物名"), p.drawString(100, 400, item.item_class_L + " " +
                                                item.item_class_M + " " +
                                                item.item_class_S)

    p.drawString(20, 300, "※記載された個人情報は、お客様へのご連絡以外の目的には利用いたしません。")

    # 担当者記入欄
    p.drawString(20, 120, "担当者記入欄")
    p.drawString(30, 95, "本人確認書類    □運転免許証   □パスポート   □保険証   □その他(______________)")
    p.drawString(30, 70, "返還担当者署名    ______________________________________     印")
    p.showPage()
    p.save()

    return "making PDF"


# 拾得物の返還/遺失者連絡
@return_item.route("/item/<item_id>", methods=["POST", "GET"])
def item(item_id):
    lostitem = LostItem.query.filter_by(id=item_id).first()
    return render_template("return_item/index.html", lostitem=lostitem)


# 遺失者連絡
@return_item.route("/item/<item_id>/note", methods=["POST", "GET"])
def note(item_id):
    lostitem = LostItem.query.filter_by(id=item_id).first()

    # Userの一覧取得
    users = User.query.all()
    user_choice = [(user.username) for user in users]
    form = LostNote()
    form.recep_manager.choices = user_choice
    form.note_manager.choices = user_choice

    if form.submit.data:
        lostitem.item_situation = "遺失者連絡済み"
        lostitem.lost_date = form.lost_date.data
        lostitem.lost_hour = form.lost_hour.data
        lostitem.lost_minute = form.lost_minute.data
        lostitem.lost_area = form.lost_area.data
        lostitem.recep_item = form.recep_item.data
        lostitem.recep_item_hour = form.recep_item_hour.data
        lostitem.recep_item_minute = form.recep_item_minute.data
        lostitem.recep_manager = form.recep_manager.data
        lostitem.lost_person = form.lost_person.data
        lostitem.lost_class = form.lost_class.data
        lostitem.lost_affiliation = form.lost_affiliation.data
        lostitem.lost_tel1 = form.lost_tel1.data
        lostitem.lost_tel2 = form.lost_tel2.data
        lostitem.lost_post = form.lost_post.data
        lostitem.lost_address = form.lost_address.data
        lostitem.note_date = form.note_date.data
        lostitem.note_hour = form.note_hour.data
        lostitem.note_minute = form.note_minute.data
        lostitem.note_process = form.note_process.data
        lostitem.note_manager = form.note_manager.data
        lostitem.response_date = form.response_date.data
        lostitem.response_hour = form.response_hour.data
        lostitem.response_minute = form.response_minute.data
        lostitem.response_expect = form.response_expect.data
        lostitem.response_content = form.response_content.data
        lostitem.response_remarks = form.response_remarks.data
        db.session.add(lostitem)
        db.session.commit()
        return redirect(url_for('return_item.item', item_id=lostitem.id))
    return render_template("return_item/note.html", lostitem=lostitem, form=form)


# 返還処理
@return_item.route("/item/<item_id>/return_item", methods=["POST", "GET"])
def item_return(item_id):
    lostitem = LostItem.query.filter_by(id=item_id).first()
    # Userの一覧取得
    users = User.query.all()
    user_choice = [(user.username) for user in users]
    form = ReturnItemForm()
    form.return_manager.choices = user_choice

    if form.submit.data:
        lostitem.item_situation = "返還済み"
        lostitem.return_date = form.return_date.data
        lostitem.return_check = form.return_check.data
        lostitem.return_person = form.return_person.data
        lostitem.return_address = form.return_address.data
        lostitem.return_tel = form.return_tel.data
        lostitem.return_manager = form.return_manager.data
        db.session.add(lostitem)
        db.session.commit()
        return redirect(url_for('return_item.item', item_id=lostitem.id))
    return render_template("return_item/return_item.html", lostitem=lostitem, form=form)

apps/return_item/templates/return_item/index.html
{% extends "register/base.html" %}
{% block title %}遺失者関連業務{% endblock %}
{% block content %}
<div class="block-card">
    <h2>遺失者関連業務</h2>
    <p>拾得物の遺失者への連絡業務や、返還業務を行います。</p>
    <div class="mb-3">
        <a href="{{ url_for('return_item.note', item_id=lostitem.id) }}" class="btn btn-primary">遺失者連絡</a>
        <a href="{{ url_for('return_item.item_return', item_id=lostitem.id) }}" class="btn btn-primary">返還</a>
        <a href="{{ url_for('return_item.make_pdf', item_id=lostitem.id) }}" class="btn btn-primary">受領確認書印刷</a>
        <a href="{{ url_for('items.detail', item_id=lostitem.id) }}" class="btn btn-secondary">戻る</a>
    </div>
</div>
<div class="block-card">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>管理番号(詳細)</th>
                <th>拾得日時</th>
                <th>拾得場所</th>
                <th>拾得物名/特徴</th>
                <th>色</th>
                <th>保管施設/場所</th>
                <th>状況</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a href="{{ url_for('items.detail', item_id=lostitem.id) }}">{{ lostitem.id }}</a>
                </td>
                <td>{{ lostitem.get_item.strftime('%Y/%m/%d') if lostitem.get_item is not none else "" }} {{
                    lostitem.get_item_hour }}{{
                    lostitem.get_item_minute }}</td>
                <td>{{ lostitem.find_area }}</td>
                <td>{{ lostitem.item_feature }}</td>
                <td>{{ lostitem.item_color }}</td>
                <td>{{ lostitem.item_storage }}/{{ lostitem.item_storage_place }}</td>
                <td>{{ lostitem.item_situation }}
                </td>
            </tr>
        </tbody>
    </table>
    <h4>遺失者連絡状況</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>遺失者氏名</th>
                <th>遺失者属性</th>
                <th>遺失者所属</th>
                <th>連絡先1</th>
                <th>連絡先2</th>
                <th>郵便番号</th>
                <th>住所</th>
            </tr>
            <tr>
                <th>連絡日</th>
                <th>連絡手段/相手</th>
                <th>連絡担当者</th>
                <th>返答日</th>
                <th>返還予定日</th>
                <th>返答内容</th>
                <th>備考</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ lostitem.lost_person if lostitem.lost_person!="None" else ""}}</td>
                <td>{{ lostitem.lost_class if lostitem.lost_class!="None" else "" }}</td>
                <td>{{ lostitem.lost_affiliation if lostitem.lost_affilication else "" }}</td>
                <td>{{ lostitem.lost_tel1 if lostitem.lost_tel1!="None" else "" }}</td>
                <td>{{ lostitem.lost_tel2 if lostitem.lost_tel2!="None" else "" }}</td>
                <td>{{ lostitem.lost_post if lostitem.lost_post!="None" else "" }}</td>
                <td>{{ lostitem.lost_address if lostitem.lost_address!="None" else "" }}</td>
            </tr>
            <tr>
                <td>{{ lostitem.note_date.strftime('%Y/%m/%d') if lostitem.note_date is not none else "" }}</td>
                <td>{{ lostitem.note_process if lostitem.note_process!="None" else "" }}</td>
                <td>{{ lostitem.note_manager }}</td>
                <td>{{ lostitem.response_date.strftime('%Y/%m/%d') if lostitem.response_date is not none else "" }}</td>
                <td>{{ lostitem.response_expect.strftime('%Y/%m/%d') if lostitem.response_expect is not none else "" }}</td>
                <td>{{ lostitem.response_content if lostitem.response_content!="None" else "" }}</td>
                <td>{{ lostitem.response_remarks if lostitem.response_remarks!="None" else "" }}</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}

apps/return_item/templates/return_item/note.html
{% extends "register/base.html" %}
{% block title %}遺失者連絡{% endblock %}
{% block content %}
<div class="block-card">
    <h2>遺失者連絡</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>管理番号(詳細)</th>
                <th>拾得日時</th>
                <th>拾得場所</th>
                <th>拾得物名/特徴</th>
                <th>色</th>
                <th>保管施設/場所</th>
                <th>状況</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a href="{{ url_for('items.detail', item_id=lostitem.id) }}">{{ lostitem.id }}</a>
                </td>
                <td>{{ lostitem.get_item.strftime('%Y/%m/%d') if lostitem.get_item is not none else "" }} {{
                    lostitem.get_item_hour }}{{
                    lostitem.get_item_minute }}</td>
                <td>{{ lostitem.find_area }}</td>
                <td>{{ lostitem.item_feature }}</td>
                <td>{{ lostitem.item_color }}</td>
                <td>{{ lostitem.item_storage }}/{{ lostitem.item_storage_place }}</td>
                <td>{{ lostitem.item_situation }}
                </td>
            </tr>
        </tbody>
    </table>
</div>
<form action="{{ url_for('return_item.note', item_id=lostitem.id) }}" , method="post">
    {{ form.csrf_token }}
    <div class="block-card">
        <h3>遺失者情報</h3>
        <div class="container">
            <div class="row mb-3">
                <div class="col-4">{{ form.lost_date.label }} {{ form.lost_date(value=lostitem.lost_date, class="form-set")
                    }}</div>
                <div class="col-4">{{ form.lost_hour.label }} {{ form.lost_hour(value=lostitem.lost_hour, class="form-set")
                    }}{{
                    form.lost_minute(value=lostitem.lost_minute, class="form-set") }}</div>
                <div class="col-4">{{ form.lost_area.label }} {{ form.lost_area(value=lostitem.lost_area, class="form-set")
                    }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.recep_item.label }} {{ form.recep_item(value=lostitem.recep_item,
                    class="form-set") }}</div>
                <div class="col-4">{{ form.recep_item_hour.label }} {{ form.recep_item_hour(value=lostitem.recep_item_hour,
                    class="form-set")
                    }}{{ form.recep_item_minute(value=lostitem.recep_item_minute, class="form-set") }}</div>
                <div class="col-4">{{ form.recep_manager.label }} {{ form.recep_manager(value=lostitem.recep_manager,
                    class="form-set") }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.lost_person.label }} {{ form.lost_person(value=lostitem.lost_person,
                    class="form-set") }}</div>
                <div class="col-4">{{ form.lost_class.label }} {{ form.lost_class(value=lostitem.lost_class,
                    class="form-set") }}</div>
                <div class="col-4">{{ form.lost_affiliation.label }} {{
                    form.lost_affiliation(value=lostitem.lost_affiliation, class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-6">{{ form.lost_tel1.label }} {{ form.lost_tel1(value=lostitem.lost_tel1, class="form-set")
                    }}</div>
                <div class="col-6">{{ form.lost_tel2.label }} {{ form.lost_tel2(value=lostitem.lost_tel2, class="form-set")
                    }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-6">{{ form.lost_post.label }} {{ form.lost_post(value=lostitem.lost_post, class="form-set")
                    }}</div>
                <div class="col-6">{{ form.lost_address.label }} {{ form.lost_address(value=lostitem.lost_address,
                    class="form-set") }}</div>
            </div>
        </div>
    
        <h3>連絡状況</h3>
        <div class="container">
            <div class="row mb-3">
                <div class="col-6">{{ form.note_date.label }} {{ form.note_date(value=lostitem.note_date, class="form-set")
                    }}</div>
                <div class="col-6">{{ form.note_hour.label }} {{ form.note_hour(value=lostitem.note_hour, class="form-set")
                    }}{{
                    form.note_minute(value=lostitem.note_minute, class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-6">{{ form.note_process.label }} {{ form.note_process(value=lostitem.note_process,
                    class="form-set") }}</div>
                <div class="col-6">{{ form.note_manager.label }} {{ form.note_manager(value=lostitem.note_manager,
                    class="form-set") }}</div>
            </div>
        </div>
    
        <h3>返答状況</h3>
        <div class="container">
            <div class="row mb-3">
                <div class="col-4">{{ form.response_date.label }} {{ form.response_date(value=lostitem.response_date,
                    class="form-set") }}
                </div>
                <div class="col-4">{{ form.response_hour.label }} {{ form.response_hour(value=lostitem.response_hour,
                    class="form-set") }}{{
                    form.response_minute(value=lostitem.response_minute, class="form-set") }}</div>
                <div class="col-4">{{ form.response_expect.label }} {{ form.response_expect(value=lostitem.response_expect,
                    class="form-set")
                    }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-6">{{ form.response_content.label }} {{
                    form.response_content(value=lostitem.response_content, class="form-set") }}</div>
                <div class="col-6">{{ form.response_remarks.label }} {{
                    form.response_remarks(value=lostitem.response_remarks, class="form-set") }}</div>
            </div>
        </div>
    
        <div class="text-center">
            {{ form.submit(class="btn btn-primary") }}
            <a href="{{ url_for('return_item.item', item_id=lostitem.id) }}" class="btn btn-secondary">戻る</a>
        </div>
    </div>
</form>
{% endblock %}

apps/return_item/templates/return_item/return_item.html
{% extends "register/base.html" %}
{% block title %}遺失物返還{% endblock %}
{% block content %}
<div class="block-card">
    <h2>遺失物返還</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>管理番号(詳細)</th>
                <th>拾得日時</th>
                <th>拾得場所</th>
                <th>拾得物名/特徴</th>
                <th>色</th>
                <th>保管施設/場所</th>
                <th>状況</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <a href="{{ url_for('items.detail', item_id=lostitem.id) }}">{{ lostitem.id }}</a>
                </td>
                <td>{{ lostitem.get_item.strftime('%Y/%m/%d') if lostitem.get_item is not none else "" }} {{
                    lostitem.get_item_hour }}{{
                    lostitem.get_item_minute }}</td>
                <td>{{ lostitem.find_area }}</td>
                <td>{{ lostitem.item_feature }}</td>
                <td>{{ lostitem.item_color }}</td>
                <td>{{ lostitem.item_storage }}/{{ lostitem.item_storage_place }}</td>
                <td>{{ lostitem.item_situation }}
                </td>
            </tr>
        </tbody>
    </table>
    
    <form action="{{ url_for('return_item.item_return', item_id=lostitem.id) }}" , method="post">
        {{ form.csrf_token }}
        <div class="container">
            <div class="row mb-3">
                <div class="col-4">{{ form.return_date.label }} {{ form.return_date(class="form-set") }}</div>
                <div class="col-4">{{ form.return_check.label }} {{ form.return_check(class="form-set") }}</div>
                <div class="col-4">{{ form.return_person.label }} {{ form.return_person(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.return_address.label }} {{ form.return_address(class="form-set") }}</div>
                <div class="col-4">{{ form.return_tel.label }} {{ form.return_tel(class="form-set") }}</div>
                <div class="col-4">{{ form.return_manager.label }} {{ form.return_manager(class="form-set") }}</div>
            </div>
        </div>
        <div class="text-center">
            {{ form.submit(class="btn btn-primary") }}
            <a href="{{ url_for('return_item.item', item_id=lostitem.id) }}" class="btn btn-secondary">戻る</a>
        </div>
    </form>
</div>
{% endblock %}