apps/crud/models.py
from datetime import datetime

from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from apps.app import db, login_manager


class User(db.Model, UserMixin):
    __tablename__ = "users"
    # カラム
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)

    # パスワードセットのプロパティ
    @property
    def password(self):
        raise AttributeError("読み取り不可")

    # パスワードをセット
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # パスワードチェック
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 名前の重複チェック
    def is_duplicate_username(self):
        return User.query.filter_by(username=self.username).first() is not None


# ログインしているユーザー情報を取得する関数を作成
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, length


# ユーザー新規作成、編集フォーム
class UserForm(FlaskForm):
    username = StringField(
        "ユーザー名",
        validators=[
            DataRequired(message="ユーザー名は必須です。"),
            length(max=30, message="30文字以内で入力してください。")
        ],
    )
    password = PasswordField(
        "パスワード",
        validators=[
            DataRequired(message="パスワードは必須です。")
        ],
    )
    submit = SubmitField("新規登録")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_required

from apps.app import db
from apps.crud.forms import UserForm
from apps.crud.models import User

crud = Blueprint(
    "crud",
    __name__,
    template_folder="templates",
    static_folder="static",
)


# indexエンドポイント
@crud.route("/")
@login_required
def index():
    return render_template("crud/index.html")


# ユーザー新規登録
@crud.route("/users/new", methods=["GET", "POST"])
@login_required
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(
            username=form.username.data,
            password=form.password.data,
        )
        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))
    return render_template("crud/create.html", form=form)


# ユーザー一覧
@crud.route("/users")
@login_required
def users():
    users = User.query.all()
    return render_template("crud/index.html", users=users)


# ユーザー編集
@crud.route("/users/<user_id>", methods=["POST", "GET"])
@login_required
def edit_user(user_id):
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()

    if form.validate_on_submit():
        user.username = form.username.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()

        return redirect(url_for("crud.users"))
    return render_template("crud/edit.html", user=user, form=form)


# ユーザー削除
@crud.route("/users/<user_id>/delete", methods=["POST"])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for("crud.users"))

apps/crud/templates/crud/create.html
{% extends "register/base.html" %}
{% block title %}ユーザー新規作成{% endblock %}
{% block content %}

<body>
    <h2>ユーザー新規作成</h2>
    <form action="{{ url_for('crud.create_user') }}" method="post" novalidate="novalidate">
        {{ form.csrf_token }}
        <p>
            {{ form.username.label }} {{ form.username(placeholder="ユーザー名") }}
        </p>
        {% for error in form.username.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>
            {{ form.password.label }} {{ form.password(placeholder="パスワード") }}
        </p>
        {% for error in form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
        <p>{{ form.submit() }}</p>
    </form>
</body>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "register/base.html" %}
{% block title %}ユーザー編集{% endblock %}
{% block content %}

<body>
    <div class="mx-auto lostitem-app-main">
        <div class="card lostitem-app-signup">
            <header>ユーザー編集</header>
            <section>
                <form action="{{ url_for('crud.edit_user', user_id=user.id) }}" method="post" class="form-signin">
                    {{ form.csrf_token }}
                    <p>
                        {{ form.username.label }} {{ form.username(placeholder="ユーザー名", value=user.username, size=30,
                        class="",) }}
                    </p>
                    {% for error in form.username.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    <p>
                        {{ form.password.label }} {{ form.password(placeholder="パスワード", size=30, class="
                        ",) }}
                    </p>
                    {% for error in form.username.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}
                    <p><input type="submit" value="更新" , class="btn btn-md btn-primary btn-block"></p>
                </form>
                <form action="{{ url_for('crud.delete_user', user_id=user.id) }}" method="post">
                    {{ form.csrf_token }}
                    <input type="submit" value="削除" , class="btn btn-md btn-secondary btn-block">
                </form>
            </section>
        </div>
    </div>
</body>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "register/base.html" %}
{% block title %}ユーザー一覧{% endblock %}
{% block content %}
<h2>ユーザー一覧</h2>
<div class="block-card">
    <a href="{{ url_for('auth.signup') }}">ユーザー新規作成</a>
    <table class="table table-bordered table-striped">
        <tr>
            <th>ユーザーID</th>
            <th>ユーザー名</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>
                <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
            </td>
            <td>{{ user.username }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}