apps/bundleditems/views.py
from flask import Blueprint, redirect, render_template, request, url_for

from apps.app import db
from apps.bundleditems.forms import BundledItemForm, CardNote, MoneyForm
from apps.config import ITEM_CLASS_L, ITEM_CLASS_M, ITEM_CLASS_S
from apps.crud.models import User
from apps.register.models import BundledItems, Denomination, LostItem

bundleditems = Blueprint(
    "bundleditems",
    __name__,
    template_folder="templates",
    static_folder="static",
)


# 同梱物登録
@bundleditems.route("/register/<item_id>", methods=["POST", "GET"])
def register(item_id):
    form = BundledItemForm()
    lostitem = LostItem.query.filter_by(id=item_id).first()
    if form.submit.data:
        bundleditem = BundledItems(
            item_class_L=request.form.get("item_class_L"),
            item_class_M=request.form.get("item_class_M"),
            item_class_S=request.form.get("item_class_S"),
            item_value=form.item_value.data,
            item_feature=form.item_feature.data,
            item_color=form.item_color.data,
            item_storage=form.item_storage.data,
            item_storage_place=form.item_storage_place.data,
            item_maker=form.item_maker.data,
            item_expiration=form.item_expiration.data,
            item_num=form.item_num.data,
            item_unit=form.item_unit.data,
            item_plice=form.item_plice.data,
            item_money=form.item_money.data,
            item_remarks=form.item_remarks.data,
            lostitem_id=lostitem.id,
            item_situation="保管中",
            # カードの場合は、カード情報の登録
            card_campany=form.card_campany.data,
            card_tel=form.card_tel.data,
            card_name=form.card_name.data,
            card_person=form.card_person.data,
            card_return=form.card_return.data,
            card_item=form.card_item.data,
            card_item_hour=form.card_item_hour.data,
            card_item_minute=form.card_item_minute.data,
            card_manager=form.card_manager.data,
        )
        db.session.add(bundleditem)
        db.session.commit()
        return redirect(url_for("items.detail", item_id=bundleditem.lostitem_id))
    return render_template(
        "bundleditems/register_item.html",
        form=form,
        lostitem=lostitem,
        ITEM_CLASS_L=ITEM_CLASS_L,
        ITEM_CLASS_M=ITEM_CLASS_M,
        ITEM_CLASS_S=ITEM_CLASS_S,
    )


# カード会社連絡
@bundleditems.route("/card/<item_id>", methods=["POST", "GET"])
def card(item_id):
    lostitem = LostItem.query.filter_by(id=item_id).first()
    bundleditems = BundledItems.query.filter_by(lostitem_id=item_id).all()
    # Userの一覧取得
    users = User.query.all()
    user_choice = [(user.username) for user in users]
    form = CardNote()
    form.card_manager.choices = user_choice
    if form.submit.data:
        renew_lostitem = request.form.getlist("main")
        renew_bundleds = request.form.getlist("item")
        if renew_lostitem:
            lostitem.item_situation = "連絡済み"
            lostitem.card_return = form.card_return.data
            lostitem.card_item = form.card_item.data
            lostitem.card_item_hour = request.form.get("card_item_hour")
            lostitem.card_item_minute = request.form.get("card_item_minute")
            lostitem.card_manager = form.card_manager.data
            db.session.add(lostitem)
            db.session.commit()
        for renew_bundled in renew_bundleds:
            renew_bundled = BundledItems.query.filter_by(id=renew_bundled).first()
            renew_bundled.item_situation = "連絡済み"
            renew_bundled.card_return = form.card_return.data
            renew_bundled.card_item = form.card_item.data
            renew_bundled.card_item_hour = request.form.get("card_item_hour")
            renew_bundled.card_item_minute = request.form.get("card_item_minute")
            renew_bundled.card_manager = form.card_manager.data
            db.session.add(renew_bundled)
            db.session.commit()
        return redirect(url_for("bundleditems.card", item_id=item_id))
    return render_template(
        "/bundleditems/card.html",
        lostitem=lostitem,
        bundleditems=bundleditems,
        form=form,
    )


# 同梱物編集
@bundleditems.route("/edit/<item_id>", methods=["POST", "GET"])
def edit(item_id):
    form = BundledItemForm()
    bundleditem = BundledItems.query.filter_by(id=item_id).first()
    if form.submit.data:
        # 大中小項目の実装
        bundleditem.item_class_L = request.form.get("item_class_L")
        bundleditem.item_class_M = request.form.get("item_class_M")
        bundleditem.item_class_S = request.form.get("item_class_S")

        bundleditem.item_value = form.item_value.data
        bundleditem.item_feature = form.item_feature.data
        bundleditem.item_color = form.item_color.data
        bundleditem.item_storage = form.item_storage.data
        bundleditem.item_storage_place = form.item_storage_place.data
        bundleditem.item_maker = form.item_maker.data
        bundleditem.item_expiration = form.item_expiration.data
        bundleditem.item_num = form.item_num.data
        bundleditem.item_unit = form.item_unit.data
        bundleditem.item_plice = form.item_plice.data
        bundleditem.item_money = form.item_money.data
        bundleditem.item_remarks = form.item_remarks.data

        # カード情報
        bundleditem.card_campany = form.card_campany.data
        bundleditem.card_tel = form.card_tel.data
        bundleditem.card_name = form.card_name.data
        bundleditem.card_person = form.card_person.data
        bundleditem.card_return = form.card_return.data
        bundleditem.card_item = form.card_item.data
        bundleditem.card_item_hour = form.card_item_hour.data
        bundleditem.card_item_minute = form.card_item_minute.data
        bundleditem.card_item_minute = form.card_item_minute.data
        db.session.add(bundleditem)
        db.session.commit()
        return redirect(url_for("items.detail", item_id=bundleditem.lostitem_id))
    return render_template(
        "bundleditems/edit.html",
        form=form,
        item=bundleditem,
        ITEM_CLASS_L=ITEM_CLASS_L,
        ITEM_CLASS_M=ITEM_CLASS_M,
        ITEM_CLASS_S=ITEM_CLASS_S,
    )


# 金種登録
@bundleditems.route("/money/register/<item_id>", methods=["POST", "GET"])
def money_register(item_id):
    form = MoneyForm()
    lostitem = LostItem.query.filter_by(id=item_id).first()
    if form.submit.data:
        total_yen = (
            (form.ten_thousand_yen.data or 0) * 10000
            + (form.five_thousand_yen.data or 0) * 5000
            + (form.two_thousand_yen.data or 0) * 2000
            + (form.one_thousand_yen.data or 0) * 1000
            + (form.five_hundred_yen.data or 0) * 500
            + (form.one_hundred_yen.data or 0) * 100
            + (form.fifty_yen.data or 0) * 50
            + (form.ten_yen.data or 0) * 10
            + (form.five_yen.data or 0) * 5
            + (form.one_yen.data or 0) * 1
        )
        denomination = Denomination(
            ten_thousand_yen=form.ten_thousand_yen.data,
            five_thousand_yen=form.five_thousand_yen.data,
            two_thousand_yen=form.two_thousand_yen.data,
            one_thousand_yen=form.one_thousand_yen.data,
            five_hundred_yen=form.five_hundred_yen.data,
            one_hundred_yen=form.one_hundred_yen.data,
            fifty_yen=form.fifty_yen.data,
            ten_yen=form.ten_yen.data,
            five_yen=form.five_yen.data,
            one_yen=form.one_yen.data,
            total_yen=total_yen,
            item_situation="保管中",
            # 記念硬貨
            commemorative_coin_1=form.commemorative_coin_1.data,
            commemorative_coin_1_value=form.commemorative_coin_1_value.data,
            commemorative_coin_2=form.commemorative_coin_2.data,
            commemorative_coin_2_value=form.commemorative_coin_2_value.data,
            lostitem_id=lostitem.id,
        )
        db.session.add(denomination)
        db.session.commit()
        return redirect(url_for("items.detail", item_id=denomination.lostitem_id))
    return render_template(
        "bundleditems/register_money.html", form=form, lostitem=lostitem
    )


# 金種編集
@bundleditems.route("/money/edit/<item_id>", methods=["POST", "GET"])
def money_edit(item_id):
    form = MoneyForm()
    denomination = Denomination.query.filter_by(lostitem_id=item_id).first()
    if form.submit.data:
        total_yen = (
            (form.ten_thousand_yen.data or 0) * 10000
            + (form.five_thousand_yen.data or 0) * 5000
            + (form.two_thousand_yen.data or 0) * 2000
            + (form.one_thousand_yen.data or 0) * 1000
            + (form.five_hundred_yen.data or 0) * 500
            + (form.one_hundred_yen.data or 0) * 100
            + (form.fifty_yen.data or 0) * 50
            + (form.ten_yen.data or 0) * 10
            + (form.five_yen.data or 0) * 5
            + (form.one_yen.data or 0) * 1
        )
        denomination.ten_thousand_yen = form.ten_thousand_yen.data
        denomination.five_thousand_yen = form.five_thousand_yen.data
        denomination.two_thousand_yen = form.two_thousand_yen.data
        denomination.one_thousand_yen = form.one_thousand_yen.data
        denomination.five_hundred_yen = form.five_hundred_yen.data
        denomination.one_hundred_yen = form.one_hundred_yen.data
        denomination.fifty_yen = form.fifty_yen.data
        denomination.ten_yen = form.ten_yen.data
        denomination.five_yen = form.five_yen.data
        denomination.one_yen = form.one_yen.data
        denomination.total_yen = total_yen

        # 記念硬貨
        denomination.commemorative_coin_1 = form.commemorative_coin_1.data
        denomination.commemorative_coin_1_value = form.commemorative_coin_1_value.data
        denomination.commemorative_coin_2 = form.commemorative_coin_2.data
        denomination.commemorative_coin_2_value = form.commemorative_coin_2_value.data
        db.session.add(denomination)
        db.session.commit()

apps/bundleditems/templates/bundleditems/edit.html
{% extends "register/base.html" %}
{% block title %}同梱物編集{% endblock %}
{% block content %}
<h2>同梱物編集</h2>
<form action="{{ url_for('bundleditems.edit', item_id=item.id) }}" method="post">
    {{ form.csrf_token }}
    <div class="block-card">
        <div class="container">
            <div class="row mb-3">
                <div class="col-4">
                    物件分類（大）
                    <select name="item_class_L" id="item_class_L" class="form-set">
                        {% for option in ITEM_CLASS_L %}
                        <option value="{{ option }}" {% if item.item_class_L==option %}selected{% endif %}>{{ option
                            }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-4">
                    （中）
                    <select name="item_class_M" id="item_class_M" class="form-set">
                        {% for option in ITEM_CLASS_M %}
                        <option value="{{ option['value'] }}" data-val="{{ option['data-val'] }}" {% if
                            item.item_class_M==option['value'] %}selected{% endif %}>{{ option['value'] }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-4">
                    （小）
                    <select name="item_class_S" id="item_class_S" class="form-set">
                        {% for option in ITEM_CLASS_S %}
                        <option value="{{ option['value'] }}" data-val="{{ option['data-val'] }}" {% if
                            item.item_class_S==option['value'] %}selected{% endif %}>{{ option['value'] }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_value.label }} {{ form.item_value(value=item.item_value) }}</div>
                <div class="col-4">{{ form.item_color.label }} {{ form.item_color(value=item.item_color) }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_storage.label }} {{ form.item_storage(value=item.item_storage) }}</div>
                <div class="col-4">{{ form.item_storage_place.label }} {{
                    form.item_storage_place(value=item.item_storage_place) }}</div>
                <div class="col-4">{{ form.item_expiration.label }} {{ form.item_expiration(value=item.item_expiration) }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_maker.label }} {{ form.item_maker(value=item.item_maker) }}</div>
                <div class="col-4">{{ form.item_num.label }} {{ form.item_num(value=item.item_num) }}</div>
                <div class="col-4">{{ form.item_unit.label }} {{ form.item_unit(value=item.item_unit) }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_plice.label }} {{ form.item_plice(value=item.item_plice) }}</div>
                <div class="col-4">{{ form.item_money.label }} {{ form.item_money(value=item.item_money) }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_remarks.label }} {{ form.item_remarks(value=item.item_remarks) }}</div>
                <div class="col-4">{{ form.item_feature.label }} {{ form.item_feature(value=item.item_feature) }}</div>
            </div>
            <p>
                <hr>
                遺失物がカードであれば、以下の項目を入力してください。<br>
                同梱物として登録する場合は、同梱物の詳細画面からカード情報を入力してください。
            </p>
            <div class="row mb-5">
                <div class="col-3">{{ form.card_campany.label }} {{ form.card_campany(value=item.card_campany) }}</div>
                <div class="col-3">{{ form.card_tel.label }} {{ form.card_tel(value=item.card_tel) }}</div>
                <div class="col-3">{{ form.card_name.label }} {{ form.card_name(value=item.card_name) }}</div>
                <div class="col-3">{{ form.card_person.label }} {{ form.card_person(value=item.card_person) }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-3">{{ form.card_item.label }} {{ form.card_item(value=item.card_item) }}</div>
                <div class="col-3">{{ form.card_return.label }} {{ form.card_return(value=item.card_return) }}</div>
                <div class="col-3">{{ form.card_item_hour.label }} {{ form.card_item_hour(value=item.card_item_hour) }}
                </div>
                <div class="col-3">{{ form.card_item_minute.label }} {{ form.card_item_minute(value=item.card_item_minute)
                    }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-3">{{ form.card_manager.label }} {{ form.card_manager(value=item.card_manager) }}</div>
            </div>
            <div class="text-center">
                {{ form.submit(value="編集",class="btn btn-primary") }}
                <a href="{{ url_for('bundleditems.delete_bundled', item_id=item.id) }}" class="btn btn-secondary">削除</a>
            </div>
        </div>
    </div> 
</form>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}

apps/bundleditems/templates/bundleditems/money_edit.html
{% extends "register/base.html" %}
{% block title %}金種編集{% endblock %}
{% block content %}
<div class="block-card">
    <h2>金種編集</h2>
    <form action="{{ url_for('bundleditems.money_edit', item_id=denomination.lostitem_id) }}" method="post">
        {{ form.csrf_token }}
        <div class="container">
            <table>
                <thead>
                    <tr>
                        <th>一万円</th>
                        <th>五千円</th>
                        <th>二千円</th>
                        <th>千円</th>
                        <th>五百円</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>{{ form.ten_thousand_yen(value=denomination.ten_thousand_yen) }}</th>
                        <th>{{ form.five_thousand_yen(value=denomination.five_thousand_yen) }}</th>
                        <th>{{ form.two_thousand_yen(value=denomination.two_thousand_yen) }}</th>
                        <th>{{ form.one_thousand_yen(value=denomination.one_thousand_yen) }}</th>
                        <th>{{ form.five_hundred_yen(value=denomination.five_hundred_yen) }}</th>
                    </tr>
                </tbody>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>百円</th>
                        <th>五十円</th>
                        <th>十円</th>
                        <th>五円</th>
                        <th>一円</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>{{ form.one_hundred_yen(value=denomination.one_hundred_yen) }}</th>
                        <th>{{ form.fifty_yen(value=denomination.fifty_yen) }}</th>
                        <th>{{ form.ten_yen(value=denomination.ten_yen) }}</th>
                        <th>{{ form.five_yen(value=denomination.five_yen) }}</th>
                        <th>{{ form.one_yen(value=denomination.one_yen) }}</th>
                    </tr>
                </tbody>
            </table>
            <table>
                <thead>
                    <tr>
                        <th>記念硬貨名</th>
                        <th>金額</th>
                        <th>記念硬貨名</th>
                        <th>金額</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>{{ form.commemorative_coin_1(value=denomination.commemorative_coin_1) }}</th>
                        <th>{{ form.commemorative_coin_1_value(value=denomination.commemorative_coin_1_value) }}</th>
                        <th>{{ form.commemorative_coin_2(value=denomination.commemorative_coin_2) }}</th>
                        <th>{{ form.commemorative_coin_2_value(value=denomination.commemorative_coin_2_value) }}</th>
                    </tr>
                </tbody>
            </table>
            <div class="text-center">
                {{ form.submit(class="btn btn-primary", value="編集") }}
                <a href="{{ url_for('bundleditems.delete', item_id=denomination.id) }}" class="btn btn-secondary">削除</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

apps/bundleditems/templates/bundleditems/register_item.html
{% extends "register/base.html" %}
{% block title %}同梱物の登録{% endblock %}
{% block content %}
<div class="block-card">
    <h2>同梱物の登録</h2>
    <form action="{{ url_for('bundleditems.register', item_id=lostitem.id) }}" method="post">
        {{ form.csrf_token }}
        <div class="container">
            <div class="row mb-3">
                <div class="col-4">
                    物件分類（大）
                    <select name="item_class_L" id="item_class_L" class="form-set">
                        {% for option in ITEM_CLASS_L %}
                        <option value="{{ option }}">{{ option }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-4">
                    （中）
                    <select name="item_class_M" id="item_class_M" class="form-set">
                        {% for option in ITEM_CLASS_M %}
                        <option value="{{ option['value'] }}" data-val="{{ option['data-val'] }}">{{ option['value'] }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-4">
                    （小）
                    <select name="item_class_S" id="item_class_S" class="form-set">
                        {% for option in ITEM_CLASS_S %}
                        <option value="{{ option['value'] }}" data-val="{{ option['data-val'] }}">{{ option['value'] }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_value.label }} {{ form.item_value(class="form-set") }}</div>
                <div class="col-4">{{ form.item_color.label }} {{ form.item_color(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_storage.label }} {{ form.item_storage(class="form-set") }}</div>
                <div class="col-4">{{ form.item_storage_place.label }} {{ form.item_storage_place(class="form-set") }}</div>
                <div class="col-4">{{ form.item_expiration.label }} {{ form.item_expiration(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_maker.label }} {{ form.item_maker(class="form-set") }}</div>
                <div class="col-4">{{ form.item_num.label }} {{ form.item_num(class="form-set") }}</div>
                <div class="col-4">{{ form.item_unit.label }} {{ form.item_unit(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-4">{{ form.item_plice.label }} {{ form.item_plice(class="form-set") }}</div>
                <div class="col-4">{{ form.item_money.label }} {{ form.item_money(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-6">{{ form.item_remarks.label }} {{ form.item_remarks(style="width:
                    500px;",class="form-set") }}</div>
                <div class="col-6">{{ form.item_feature.label }} {{ form.item_feature(style="width:
                    500px;",class="form-set") }}</div>
            </div>
            <p>
                <hr>
                遺失物がカードであれば、以下の項目を入力してください。<br>
                同梱物として登録する場合は、同梱物の詳細画面からカード情報を入力してください。
            </p>
            <div class="row mb-5">
                <div class="col-3">{{ form.card_campany.label }} {{ form.card_campany(class="form-set") }}</div>
                <div class="col-3">{{ form.card_tel.label }} {{ form.card_tel(class="form-set") }}</div>
                <div class="col-3">{{ form.card_name.label }} {{ form.card_name(class="form-set") }}</div>
                <div class="col-3">{{ form.card_person.label }} {{ form.card_person(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-3">{{ form.card_item.label }} {{ form.card_item(class="form-set") }}</div>
                <div class="col-3">{{ form.card_return.label }} {{ form.card_return(class="form-set") }}</div>
                <div class="col-3">{{ form.card_item_hour.label }} {{ form.card_item_hour(class="form-set") }}{{
                    form.card_item_minute(class="form-set") }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-3">{{ form.card_manager.label }} {{ form.card_manager(class="form-set") }}</div>
            </div>
            <div class="text-center">
                {{ form.submit(class="btn btn-primary") }}
                <a href="{{ url_for('items.detail', item_id=lostitem.id) }}" class="btn btn-secondary">戻る</a>
            </div>
        </div>
    </form>
</div>
<script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}

apps/bundleditems/templates/bundleditems/register_money.html
{% extends "register/base.html" %}
{% block title %}金種登録{% endblock %}
{% block content %}
<h2>金種登録</h2>
<form action="{{ url_for('bundleditems.money_register', item_id=lostitem.id) }}" method="post">
    {{ form.csrf_token }}
    <div class="container">
        <table>
            <thead>
                <tr>
                    <th>一万円</th>
                    <th>五千円</th>
                    <th>二千円</th>
                    <th>千円</th>
                    <th>五百円</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>{{ form.ten_thousand_yen(class="form-set") }}</th>
                    <th>{{ form.five_thousand_yen(class="form-set") }}</th>
                    <th>{{ form.two_thousand_yen(class="form-set") }}</th>
                    <th>{{ form.one_thousand_yen(class="form-set") }}</th>
                    <th>{{ form.five_hundred_yen(class="form-set") }}</th>
                </tr>
            </tbody>
        </table>
        <table>
            <thead>
                <tr>
                    <th>百円</th>
                    <th>五十円</th>
                    <th>十円</th>
                    <th>五円</th>
                    <th>一円</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>{{ form.one_hundred_yen(class="form-set") }}</th>
                    <th>{{ form.fifty_yen(class="form-set") }}</th>
                    <th>{{ form.ten_yen(class="form-set") }}</th>
                    <th>{{ form.five_yen(class="form-set") }}</th>
                    <th>{{ form.one_yen(class="form-set") }}</th>
                </tr>
            </tbody>
        </table>
        <table>
            <thead>
                <tr>
                    <th>記念硬貨名</th>
                    <th>金額</th>
                    <th>記念硬貨名</th>
                    <th>金額</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>{{ form.commemorative_coin_1(class="form-set") }}</th>
                    <th>{{ form.commemorative_coin_1_value(class="form-set") }}</th>
                    <th>{{ form.commemorative_coin_2(class="form-set") }}</th>
                    <th>{{ form.commemorative_coin_2_value(class="form-set") }}</th>
                </tr>
            </tbody>
        </table>
        <div class="text-center">
            {{ form.submit(class="btn btn-primary") }}
            <a href="{{ url_for('items.detail', item_id=lostitem.id) }}" class="btn btn-secondary">戻る</a>
        </div>
    </div>
</form>
{% endblock %}